#!/usr/bin/env bash
# This code was generated by the devconainer-contrib cli 
# For more information: https://github.com/devcontainers-contrib/cli 

set -e

ensure_curl () {
    if ! type curl >/dev/null 2>&1; then
        apt-get update -y && apt-get -y install --no-install-recommends curl
    fi 
}

ensure_curl

PLUGIN="erlang" VERSION="$VERSION" source <(curl -s "https://raw.githubusercontent.com/devcontainers-contrib/cli/main/resources/install-feature.sh") "ghcr.io/devcontainers-contrib/features/asdf-package:1.0.0"

PACKAGES="build-essential autoconf m4 libncurses5-dev libwxgtk3.0-gtk3-dev libwxgtk-webview3.0-gtk3-dev libgl1-mesa-dev libglu1-mesa-dev libpng-dev libssh-dev unixodbc-dev xsltproc fop libxml2-utils libncurses-dev openjdk-11-jdk" source <(curl -s "https://raw.githubusercontent.com/devcontainers-contrib/cli/main/resources/install-feature.sh") "ghcr.io/devcontainers-contrib/features/apt-get-packages:1.0.0"
